### ISSUE TITLE
Should is_int() return true for all integers? Same for is_number().

### ISSUE THREAD

**Issue by alwaysmpe** [ar90n/msgpack11#5]
Looking at the implementation of MsgPack is_int() it only returns true for int_32_t

To me the logical approach would be to mimic JSON type specification, ie is_int() would return true for all encoded int types (including unsigned) and is_number() should return true for all numbers (floats and ints).

therefore change is_int() to:
    is_int(){ return is_int8() || is_int16() || is_int32() || is_int64() || is_uint8 || is_uint16 || is_uint32() || is_uint64();}
and is_number() to:
   is_number(){return is_float32() || is_float64() || is_int();}

It might be possible to make this cleaner using bitmasks but I've not had coffee yet so can't think.

But thanks for a nice c++11 friendly implementation!

**Comment by alwaysmpe** [comment]
Additionally once this is then dumped to string data it's encoded as the smallest possible value type. Therefore when an instance of MsgPack is constructed from an int it returns true to is_int(), however when that instance is then encoded and decoded it returns false.

**Comment by ar90n** [comment]
Close this issue by merging this PR.
